name: Calendar-Spread Scan

on:
  # Nightly at 8 PM US-Eastern  ➜  00:00 UTC (during EDT)
  schedule:
    - cron: '0 0 * * *'
  # Manual “Run workflow” button
  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: write         # allow the bot to push the CSV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run screener
        env:
          TG_TOKEN:      ${{ secrets.TG_TOKEN }}
          TG_CHAT:       ${{ secrets.TG_CHAT }}
          TRADIER_TOKEN: ${{ secrets.TRADIER_TOKEN }}
        run: python scan.py

      - name: Commit CSV back to repo
        if: ${{ success() }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add list*.csv
          # The [skip ci] tag prevents this push from triggering any workflows
          git commit -m "data: add results $(date +%F) [skip ci]" \
            || echo "nothing to commit"
          git push origin HEAD:${{ github.ref }}

