# .github/workflows/calendar_scan.yml
name: Calendar-Spread Scan

on:
  schedule:
    # 8 PM America/New_York = 00:00 UTC during EDT
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scan:
    permissions: { contents: write }     # allow git push with GITHUB_TOKEN
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - run: pip install -r requirements.txt

      - name: Run screener
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT:  ${{ secrets.TG_CHAT }}
        run: python scan.py

      - name: Commit CSV back to repo
        if: ${{ success() }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add list*.csv
          git commit -m "Add results for $(date +%F)" || echo "nothing to commit"
          git push origin HEAD:${{ github.ref }}
